name: Build FastFinder for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [amd64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install MSYS2 and Dependencies
        uses: msys2/setup-msys2@v2
        with:
          location: C:\msys64
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkg-config
            base-devel
            openssl-devel
            unzip

      - name: Set Environment Variables
        run: |
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "GOOS=windows" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-IC:/msys64/mingw64/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-LC:/msys64/mingw64/lib -lyara -lcrypto" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=C:/msys64/mingw64/lib/pkgconfig" >> $GITHUB_ENV
          echo "C:\msys64\mingw64\bin" | Out-File -Append -Encoding utf8 -FilePath $env:GITHUB_PATH
        shell: powershell

      - name: Download and Compile libyara
        uses: msys2/setup-msys2@v2
        with:
          location: C:\msys64
          msystem: MINGW64
          install: >-
            base-devel
            autoconf
            automake
            libtool

      - name: Get MSYS2 Location
        uses: msys2/setup-msys2@v2
        id: msys2
        env:
          MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
          run: echo "$env:MSYS2_LOCATION"    
        
      - name: Build libyara
        run: |
          curl -LO https://github.com/VirusTotal/yara/archive/refs/tags/v4.4.0.zip
          unzip v4.4.0.zip
          cd yara-4.4.0
          ./bootstrap.sh
          ./configure
          make
          make install
        shell: msys2 {0}

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set GOPATH
        run: echo "GOPATH=$env:USERPROFILE\go" | Out-File -Append -Encoding utf8 -FilePath $env:GITHUB_ENV
        shell: powershell

      - name: Build FastFinder
        run: go build -tags yara_static -a -ldflags '-extldflags "-static"' .
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fastfinder-${{ matrix.arch }}
          path: fastfinder.exe
